### ISSUE TITLE
Módulo 3. Algoritmos Computacionais

### ISSUE THREAD

**Issue by stonestecnologia** [balta-io/7183#1]
**Módulo 3. Algoritmos Computacionais Aula 1. Instalando uma IDE (VSCode)**

Boa tarde, nesta aula vc nao fala sobre os plugins necessarios !!
Tem alguma aula especifica ?

**Comment by andrebaltieri** [comment]
Boa tarde @stonestecnologia !
Temos um artigo explicando como instalar e configurar o VS Code aqui:
https://balta.io/blog/visual-studio-code-instalacao-customizacao

Instalação do Flutter no Windows:
https://balta.io/blog/flutter-instalacao-configuracao-android-windows

Instalação do Flutter no MacOs:
https://balta.io/blog/comecando-com-flutter-instalacao-macos
